#!/bin/bash
#SBATCH --chdir /home/william/deep-person-reid
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem 8G
#SBATCH --partition gpu
#SBATCH --gres gpu:1
#SBATCH --qos dlav
#SBATCH --account civil-459-2023
#SBATCH --time 72:00:00

conda deactivate
source /home/william/venv/torchreid2/bin/activate

module load gcc/8.4.0-cuda cuda/11.6.2

nvidia-smi
which python
nvcc -V
python -V

/home/william/venv/torchreid2/bin/python deep-person-reid/scripts/main.py --config-file deep-person-reid/configs/im_osnet_x1_0_softmax_single_amsgrad_nuscenes.yaml --transforms random_flip --root /work/scitas-share/datasets/Vita/civil-459/nuscenes_reid